import type { Expediente } from "@/lib/types";

export const hospitalLima: Expediente = {
  id: "exp-hospital-lima",
  nombreProyecto: "Hospital de Lima – Proyecto de Construcción",
  broker: "Seguros Globales",
  ejecutivo: "Mariana Torres",
  creadoEn: "2026-06-27T09:00:00-05:00",
  actualizadoEn: "2026-07-29T10:24:00-05:00",
  estado: "en_analisis",
  tiempoAhorradoMin: 38,
  consorcioDetectado: {
    empresas: 2,
    nombres: ["Constructora ABC S.A.C.", "Ingeniería del Perú S.A."],
  },
  readyScore: {
    valor: 92,
    etiqueta: "Listo para evaluación",
    factores: [
      { id: "documentacion", label: "Documentación", valor: 89, peso: 0.3 },
      { id: "validaciones", label: "Validaciones externas", valor: 95, peso: 0.25 },
      { id: "experiencia", label: "Experiencia (SEACE)", valor: 91, peso: 0.2 },
      { id: "equifax", label: "Equifax", valor: 97, peso: 0.15 },
      { id: "consistencia", label: "Consistencia de datos", valor: 94, peso: 0.1 },
    ],
  },
  confianzaIA: {
    valor: 96,
    mensaje: "Expediente listo para evaluación.",
  },
  riesgos: [
    {
      id: "documental",
      titulo: "Riesgo Documental",
      nivel: "bajo",
      descripcion: "2 documentos pendientes de un total de 17.",
      detalle: [
        "Falta EEFF Situacional con notas.",
        "Falta Carta de Nombramiento del representante del consorcio.",
      ],
    },
    {
      id: "financiero",
      titulo: "Riesgo Financiero",
      nivel: "bajo",
      descripcion: "Patrimonio y liquidez consistentes con el monto referencial.",
      detalle: [
        "Patrimonio declarado S/ 8,450,000 cubre el 34% del monto referencial.",
        "Equifax sin alertas críticas de comportamiento de pago.",
      ],
    },
    {
      id: "legal",
      titulo: "Riesgo Legal",
      nivel: "medio",
      descripcion: "Vigencia de poder próxima a vencer en uno de los consorciados.",
      detalle: [
        "Vigencia de poder de Constructora ABC vence en 22 días.",
        "Sin sanciones ni inhabilitaciones registradas en OSCE.",
      ],
    },
    {
      id: "operativo",
      titulo: "Riesgo Operativo",
      nivel: "bajo",
      descripcion: "Experiencia técnica alineada al objeto del proyecto.",
      detalle: [
        "61 de 82 contratos analizados corresponden a infraestructura hospitalaria.",
        "Equipo técnico acreditado en Bases Integradas.",
      ],
    },
  ],
  executiveBrief: {
    generadoEn: "2026-07-29T10:24:00-05:00",
    parrafos: [
      "El expediente corresponde al proyecto de construcción del Hospital de Lima, convocado por el MINSA por un monto referencial de S/ 25,000,000. Se identificó un consorcio de 2 empresas: Constructora ABC S.A.C. (60% de participación) e Ingeniería del Perú S.A. (40%).",
      "La constructora líder se encuentra activa y habida ante SUNAT, sin deuda coactiva ni sanciones registradas ante OSCE. El reporte Equifax no muestra alertas críticas y el score de comportamiento de pago es sólido.",
      "La experiencia técnica declarada muestra alta compatibilidad con el objeto del proyecto: 61 de 82 contratos ejecutados corresponden a infraestructura hospitalaria, lo que respalda la capacidad operativa del consorcio.",
      "El estado documental se encuentra en 92%, con 2 documentos pendientes que no comprometen el inicio del análisis pero deben regularizarse antes de la emisión.",
    ],
    montoReferencial: 25_000_000,
    entidad: "MINSA",
    estadoDocumentalPct: 92,
    pendientes: ["EEFF Situacional, con Notas", "Carta de Nombramiento"],
    recomendacion:
      "El expediente está en condiciones de iniciar evaluación. Se recomienda solicitar al broker los 2 documentos faltantes en paralelo, sin bloquear el análisis inicial.",
  },
  insights: [
    { id: "i1", texto: "Empresa activa y habida ante SUNAT.", tono: "success" },
    { id: "i2", texto: "No registra deuda coactiva.", tono: "success" },
    { id: "i3", texto: "No registra sanciones en OSCE.", tono: "success" },
    { id: "i4", texto: "Cuenta con amplia experiencia en infraestructura hospitalaria.", tono: "success" },
    { id: "i5", texto: "Falta Carta de Nombramiento del representante del consorcio.", tono: "warning" },
    { id: "i6", texto: "Equifax sin alertas críticas.", tono: "success" },
    { id: "i7", texto: "Vigencia de poder próxima a vencer (22 días).", tono: "warning" },
    { id: "i8", texto: "Experiencia altamente compatible con el objeto del proyecto (91%).", tono: "success" },
  ],
  checklist: [
    {
      id: "cliente",
      titulo: "Cliente",
      items: [
        { id: "c1", label: "F1 - Ficha básica de cliente PJ", estado: "completo", tipoDetectado: "F1_FICHA_BASICA" },
        { id: "c2", label: "F2 - Declaración de experiencia", estado: "completo", tipoDetectado: "F2_DECLARACION_EXPERIENCIA" },
        { id: "c3", label: "F3 - DJ patrimonial (Accionistas)", estado: "completo", tipoDetectado: "F3_DJ_PATRIMONIAL" },
        { id: "c4", label: "DNI", estado: "completo", tipoDetectado: "DNI" },
        { id: "c5", label: "DDJJ", estado: "completo", tipoDetectado: "DECLARACION_JURADA" },
        { id: "c6", label: "EEFF Situacional, con Notas", estado: "pendiente", tipoDetectado: "EEFF_SITUACIONAL" },
        { id: "c7", label: "Vigencia Poder (≤ 30 días)", estado: "advertencia", tipoDetectado: "VIGENCIA_PODER", notas: "Vence en 22 días" },
        { id: "c8", label: "Copia Literal", estado: "completo", tipoDetectado: "COPIA_LITERAL" },
        { id: "c9", label: "Carta de Nombramiento", estado: "pendiente", tipoDetectado: "CARTA_NOMBRAMIENTO" },
      ],
    },
    {
      id: "proyecto",
      titulo: "Proyecto",
      items: [
        { id: "p1", label: "Solicitud de emisión", estado: "completo", tipoDetectado: "SOLICITUD_EMISION" },
        { id: "p2", label: "Bases Integradas", estado: "completo", tipoDetectado: "BASES_INTEGRADAS" },
        { id: "p3", label: "Memoria Descriptiva", estado: "completo", tipoDetectado: "MEMORIA_DESCRIPTIVA" },
        { id: "p4", label: "Presupuesto - Público", estado: "completo", tipoDetectado: "PRESUPUESTO" },
        { id: "p5", label: "Reporte de Buena Pro", estado: "completo", tipoDetectado: "REPORTE_BUENA_PRO" },
        { id: "p6", label: "Acta de Buena Pro", estado: "completo", tipoDetectado: "ACTA_BUENA_PRO" },
      ],
    },
    {
      id: "consorcio",
      titulo: "Consorcio",
      items: [
        { id: "k1", label: "Ficha básica del consorcio", estado: "completo", tipoDetectado: "FICHA_CONSORCIO" },
        { id: "k2", label: "Contrato de Consorcio", estado: "completo", tipoDetectado: "CONTRATO_CONSORCIO" },
      ],
    },
    {
      id: "validaciones",
      titulo: "Validaciones Externas",
      items: [
        { id: "v1", label: "Consulta RUC (SUNAT)", estado: "completo", tipoDetectado: "CONSULTA_RUC" },
        { id: "v2", label: "Consulta Deuda Coactiva", estado: "completo", tipoDetectado: "CONSULTA_DEUDA_COACTIVA" },
        { id: "v3", label: "Proveedores del Estado (OSCE)", estado: "completo", tipoDetectado: "CONSULTA_PROVEEDORES_ESTADO" },
        { id: "v4", label: "Experiencia SEACE", estado: "completo", tipoDetectado: "EXPERIENCIA_SEACE" },
        { id: "v5", label: "Reporte Equifax", estado: "completo", tipoDetectado: "REPORTE_EQUIFAX" },
      ],
    },
  ],
  documentos: [
    { id: "d1", nombre: "F1_Ficha_Basica_Constructora_ABC.pdf", extension: "pdf", tamanioBytes: 2_516_582, subidoEn: "2026-06-27T14:02:00-05:00", categoria: "cliente", tipoDetectado: "F1_FICHA_BASICA", confianzaDeteccion: 0.98, estado: "completo" },
    { id: "d2", nombre: "F2_Declaracion_Experiencia_Constructora_ABC.pdf", extension: "pdf", tamanioBytes: 1_887_436, subidoEn: "2026-06-27T14:02:00-05:00", categoria: "cliente", tipoDetectado: "F2_DECLARACION_EXPERIENCIA", confianzaDeteccion: 0.97, estado: "completo" },
    { id: "d3", nombre: "DNI_Representante_Legal.pdf", extension: "pdf", tamanioBytes: 1_258_291, subidoEn: "2026-06-27T14:03:00-05:00", categoria: "cliente", tipoDetectado: "DNI", confianzaDeteccion: 0.99, estado: "completo" },
    { id: "d4", nombre: "Vigencia_Poder_Constructora_ABC.pdf", extension: "pdf", tamanioBytes: 1_572_864, subidoEn: "2026-06-27T14:03:00-05:00", categoria: "cliente", tipoDetectado: "VIGENCIA_PODER", confianzaDeteccion: 0.95, estado: "advertencia" },
    { id: "d5", nombre: "C1_Solicitud_Emision_Hospital_Lima.pdf", extension: "pdf", tamanioBytes: 2_097_152, subidoEn: "2026-06-27T14:05:00-05:00", categoria: "proyecto", tipoDetectado: "SOLICITUD_EMISION", confianzaDeteccion: 0.96, estado: "completo" },
    { id: "d6", nombre: "Bases_Integradas_MINSA.pdf", extension: "pdf", tamanioBytes: 6_291_456, subidoEn: "2026-06-27T14:06:00-05:00", categoria: "proyecto", tipoDetectado: "BASES_INTEGRADAS", confianzaDeteccion: 0.93, estado: "completo" },
    { id: "d7", nombre: "Memoria_Descriptiva_HospitalLima.docx", extension: "docx", tamanioBytes: 984_231, subidoEn: "2026-06-27T14:07:00-05:00", categoria: "proyecto", tipoDetectado: "MEMORIA_DESCRIPTIVA", confianzaDeteccion: 0.9, estado: "completo" },
    { id: "d8", nombre: "Presupuesto_Publico_2026.xlsx", extension: "xlsx", tamanioBytes: 421_120, subidoEn: "2026-06-27T14:08:00-05:00", categoria: "proyecto", tipoDetectado: "PRESUPUESTO", confianzaDeteccion: 0.94, estado: "completo" },
    { id: "d9", nombre: "Acta_Buena_Pro_Consorcio.pdf", extension: "pdf", tamanioBytes: 1_048_576, subidoEn: "2026-06-27T14:09:00-05:00", categoria: "proyecto", tipoDetectado: "ACTA_BUENA_PRO", confianzaDeteccion: 0.97, estado: "completo" },
    { id: "d10", nombre: "Contrato_Consorcio_ABC_IngenieriaPeru.pdf", extension: "pdf", tamanioBytes: 1_363_149, subidoEn: "2026-06-27T14:10:00-05:00", categoria: "consorcio", tipoDetectado: "CONTRATO_CONSORCIO", confianzaDeteccion: 0.96, estado: "completo" },
    { id: "d11", nombre: "Ficha_Consorcio_Hospital_Lima.pdf", extension: "pdf", tamanioBytes: 786_432, subidoEn: "2026-06-27T14:10:00-05:00", categoria: "consorcio", tipoDetectado: "FICHA_CONSORCIO", confianzaDeteccion: 0.95, estado: "completo" },
    { id: "d12", nombre: "Consulta_RUC_SUNAT_20123456789.pdf", extension: "pdf", tamanioBytes: 312_780, subidoEn: "2026-06-28T09:15:00-05:00", categoria: "validaciones", tipoDetectado: "CONSULTA_RUC", confianzaDeteccion: 0.99, estado: "completo" },
    { id: "d13", nombre: "Consulta_Deuda_Coactiva_SUNAT.png", extension: "png", tamanioBytes: 542_218, subidoEn: "2026-06-28T09:16:00-05:00", categoria: "validaciones", tipoDetectado: "CONSULTA_DEUDA_COACTIVA", confianzaDeteccion: 0.92, estado: "completo" },
    { id: "d14", nombre: "Reporte_Proveedores_Estado_OSCE.pdf", extension: "pdf", tamanioBytes: 674_309, subidoEn: "2026-06-28T09:20:00-05:00", categoria: "validaciones", tipoDetectado: "CONSULTA_PROVEEDORES_ESTADO", confianzaDeteccion: 0.94, estado: "completo" },
    { id: "d15", nombre: "Experiencia_SEACE_ConstructoraABC.xlsx", extension: "xlsx", tamanioBytes: 891_022, subidoEn: "2026-06-28T09:30:00-05:00", categoria: "validaciones", tipoDetectado: "EXPERIENCIA_SEACE", confianzaDeteccion: 0.96, estado: "completo" },
    { id: "d16", nombre: "Reporte_Equifax_ConstructoraABC.pdf", extension: "pdf", tamanioBytes: 1_887_437, subidoEn: "2026-06-28T09:35:00-05:00", categoria: "validaciones", tipoDetectado: "REPORTE_EQUIFAX", confianzaDeteccion: 0.98, estado: "completo" },
    { id: "d17", nombre: "Copia_Literal_ConstructoraABC.pdf", extension: "pdf", tamanioBytes: 1_048_576, subidoEn: "2026-06-27T14:04:00-05:00", categoria: "cliente", tipoDetectado: "COPIA_LITERAL", confianzaDeteccion: 0.93, estado: "completo" },
  ],
  evidencias: [
    {
      id: "e1",
      nombreArchivo: "Consulta_RUC_SUNAT_20123456789.pdf",
      tipoDetectado: "CONSULTA_RUC",
      tituloVisible: "Consulta RUC",
      subidoEn: "2026-06-28T09:15:00-05:00",
      estado: "completo",
      resultados: [
        { etiqueta: "Estado", valor: "Activo", tono: "success" },
        { etiqueta: "Condición", valor: "Habido", tono: "success" },
      ],
      resumenIA: "RUC 20123456789 activo y habido. Sin observaciones ante SUNAT.",
    },
    {
      id: "e2",
      nombreArchivo: "Consulta_Deuda_Coactiva_SUNAT.png",
      tipoDetectado: "CONSULTA_DEUDA_COACTIVA",
      tituloVisible: "Consulta Deuda Coactiva",
      subidoEn: "2026-06-28T09:16:00-05:00",
      estado: "completo",
      resultados: [{ etiqueta: "Resultado", valor: "Sin deuda", tono: "success" }],
      resumenIA: "No se registra deuda coactiva exigible a la fecha de consulta.",
    },
    {
      id: "e3",
      nombreArchivo: "Reporte_Proveedores_Estado_OSCE.pdf",
      tipoDetectado: "CONSULTA_PROVEEDORES_ESTADO",
      tituloVisible: "Proveedores del Estado (OSCE)",
      subidoEn: "2026-06-28T09:20:00-05:00",
      estado: "completo",
      resultados: [
        { etiqueta: "Estado registral", valor: "Hábil", tono: "success" },
        { etiqueta: "Sanciones", valor: "Ninguna", tono: "success" },
      ],
      resumenIA: "Proveedor hábil ante OSCE, sin inhabilitaciones ni sanciones vigentes.",
    },
    {
      id: "e4",
      nombreArchivo: "Experiencia_SEACE_ConstructoraABC.xlsx",
      tipoDetectado: "EXPERIENCIA_SEACE",
      tituloVisible: "Experiencia SEACE",
      subidoEn: "2026-06-28T09:30:00-05:00",
      estado: "completo",
      resultados: [
        { etiqueta: "Contratos analizados", valor: "82", tono: "neutral" },
        { etiqueta: "Compatibles", valor: "61 (74%)", tono: "success" },
      ],
      resumenIA: "Alta compatibilidad con infraestructura hospitalaria. Ver Experience Match para detalle.",
    },
    {
      id: "e5",
      nombreArchivo: "Reporte_Equifax_ConstructoraABC.pdf",
      tipoDetectado: "REPORTE_EQUIFAX",
      tituloVisible: "Equifax",
      subidoEn: "2026-06-28T09:35:00-05:00",
      estado: "completo",
      resultados: [
        { etiqueta: "Score", valor: "812 / 900", tono: "success" },
        { etiqueta: "Alertas", valor: "Sin alertas críticas", tono: "success" },
      ],
      resumenIA: "Comportamiento de pago sólido. Score en rango de bajo riesgo.",
    },
  ],
  informacionExtraida: {
    razonSocial: "Constructora ABC S.A.C.",
    ruc: "20123456789",
    representanteLegal: "Juan Carlos Pérez Gómez",
    direccion: "Av. Los Constructores 123, Lima",
    correo: "jcarlos@constructorabc.com",
    actividadEconomica: "Construcción de edificios",
    patrimonio: 8_450_000,
    participacionConsorcio: 60,
  },
  experienceMatch: {
    projectFitScore: 91,
    contratosAnalizados: 82,
    contratosCompatibles: 61,
    explicacion:
      "Se analizaron 82 contratos declarados en SEACE. 61 corresponden a proyectos de infraestructura hospitalaria o de salud, lo que demuestra alta alineación con el objeto del proyecto (construcción del Hospital de Lima).",
    riesgos: [
      "12 contratos corresponden a infraestructura educativa (colegios), con menor relación directa al objeto hospitalario.",
      "9 contratos no especifican el tipo de establecimiento en la descripción SEACE; se recomienda validación manual.",
    ],
    categorias: [
      { nombre: "Infraestructura hospitalaria", cantidad: 61, pct: 74 },
      { nombre: "Infraestructura educativa", cantidad: 12, pct: 15 },
      { nombre: "Sin especificar", cantidad: 9, pct: 11 },
    ],
    contratos: [
      { id: "ct1", entidad: "MINSA - Red de Salud Lima Este", objeto: "Construcción de hospital de nivel II-1", monto: 18_200_000, anio: 2024, categoria: "Infraestructura hospitalaria", compatible: true },
      { id: "ct2", entidad: "EsSalud", objeto: "Ampliación de centro de salud", monto: 9_600_000, anio: 2023, categoria: "Infraestructura hospitalaria", compatible: true },
      { id: "ct3", entidad: "GORE Callao", objeto: "Construcción de posta médica", monto: 4_100_000, anio: 2023, categoria: "Infraestructura hospitalaria", compatible: true },
      { id: "ct4", entidad: "UGEL 03", objeto: "Construcción de I.E. primaria", monto: 6_300_000, anio: 2022, categoria: "Infraestructura educativa", compatible: false },
      { id: "ct5", entidad: "Municipalidad de Ate", objeto: "Remodelación de local comunal", monto: 1_450_000, anio: 2021, categoria: "Sin especificar", compatible: false },
    ],
  },
  equifax: {
    score: 812,
    clasificacion: "Bajo riesgo",
    riesgos: ["Concentración moderada de deuda financiera de corto plazo."],
    alertas: [],
    conclusiones: [
      "Comportamiento de pago histórico estable, sin protestos ni moras reportadas.",
      "Score de 812/900 ubica a la empresa en el rango de bajo riesgo crediticio.",
      "No se identifican alertas críticas que condicionen la emisión.",
    ],
  },
  sustentosPago: [
    { id: "s1", monto: 12_500, entidadBancaria: "BCP", fecha: "2026-06-20", beneficiario: "AVLA Seguros", observaciones: "Pago de póliza vigente sin observaciones." },
  ],
  chat: [
    {
      id: "m1",
      role: "assistant",
      content:
        "Hola, soy tu Copiloto AVLA Lens. Ya analicé el expediente del Hospital de Lima. Puedo ayudarte con documentos faltantes, riesgos, experiencia o cualquier dato extraído.",
      createdAt: "2026-07-29T10:24:00-05:00",
    },
    {
      id: "m2",
      role: "user",
      content: "¿Qué documentos faltan?",
      createdAt: "2026-07-29T10:25:00-05:00",
    },
    {
      id: "m3",
      role: "assistant",
      content:
        "Faltan 2 documentos obligatorios:\n\n• EEFF Situacional, con Notas\n• Carta de Nombramiento\n\nNinguno bloquea el inicio del análisis, pero se recomiendan antes de la emisión.",
      createdAt: "2026-07-29T10:25:05-05:00",
      suggestions: ["¿Hay documentos vencidos?", "¿Quién es el representante legal?"],
    },
  ],
};
